#!/bin/sh

# Check current governor
current_gov=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)

if [ "$current_gov" = "powersave" ]; then
    echo "Switching to performance mode"
    echo performance | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
else
    echo "Switching to powersave mode"
    echo powersave | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
fi
