#!/bin/sh

bspc monitor -d 1 2 3 4 5

bspc config border_width 2
bspc config window_gap 2
bspc config split_ratio 0.50
bspc config bottom_padding 28
bspc config focused_border_color "#FFFFFF"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

## Window rules -------------------------------#

# remove all rules first
bspc rule -r *:*

bspc rule -a firefox desktop='^2' follow=on focus=on
bspc rule -a mpv desktop='^3' follow=on focus=on
bspc rule -a Anki desktop='^4'
bspc rule -a qBittorrent desktop='^5' follow=on focus=on
bspc rule -a Connman-gtk state=floating
bspc rule -a Blueman-manager state=floating
bspc rule -a Pavucontrol state=floating

killall -9 qbittorrent polybar sxhkd xsettingsd dunst nitrogen fcitx5 xcape redshift

#nvidia-settings --assign CurrentMetaMode="nvidia-auto-select +0+0 { ForceFullCompositionPipeline = On }" &
#sudo nvidia-smi -pm1 && sudo nvidia-smi -i 0 -pl 120 &
#sudo smbios-thermal-ctl --set-thermal-mode quiet &
xset r rate 300 50 &
setxkbmap -option caps:super -variant altgr-intl &
xcape -e 'Super_L=Escape' &
xsetroot -cursor_name left_ptr &
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &
nitrogen --restore &
dunst -conf ~/.config/dunst/dunstrc &
$HOME/.config/polybar/launch.sh --hack &
clipit --daemon --no-icon &
sxhkd &
